FROM ruby:3.3.5-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev

RUN gem install bundler

COPY Gemfile Gemfile.lock ./
RUN bundle install -j4 && rm -rf /usr/local/bundle/cache

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]