# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'opentelemetry-collector'
    static_configs:
      - targets: ['collector:8889']

#  - job_name: 'rails-app'
#    static_configs:
#      - targets: ['app:3000']